_arpabet2ipa = {
    "AA": "ɑ",
    "AE": "æ",
    "AH": "ʌ",
    "AH0": "ə",
    "AO": "ɔ",
    "AW": "aʊ",
    "AY": "aɪ",
    "EH": "ɛ",
    "ER": "ɝ",
    "ER0": "ɚ",
    "EY": "eɪ",
    "IH": "ɪ",
    "IH0": "ɨ",
    "IY": "i",
    "OW": "oʊ",
    "OY": "ɔɪ",
    "UH": "ʊ",
    "UW": "u",
    "B": "b",
    "CH": "tʃ",
    "D": "d",
    "DH": "ð",
    "EL": "l̩ ",
    "EM": "m̩",
    "EN": "n̩",
    "F": "f",
    "G": "ɡ",
    "HH": "h",
    "JH": "dʒ",
    "K": "k",
    "L": "l",
    "M": "m",
    "N": "n",
    "NG": "ŋ",
    "P": "p",
    "Q": "ʔ",
    "R": "ɹ",
    "S": "s",
    "SH": "ʃ",
    "T": "t",
    "TH": "θ",
    "V": "v",
    "W": "w",
    "WH": "ʍ",
    "Y": "j",
    "Z": "z",
    "ZH": "ʒ",
}

_buckeye2ipa = _arpabet2ipa.copy()
_buckeye2ipa.pop("ER0")
_buckeye2ipa.pop("WH")
_buckeye2ipa.pop("IH0")
_buckeye2ipa.pop("Q")
_buckeye2ipa.pop("AH0")
_buckeye2ipa.update(
    {
        "ER": "ɹ̩",
        "AEN": "æ̃",
        "AON": "ɔ̃",
        "AXN": "ə̃",
        "IYN": "ĩ",
        "EYN": "ẽɪ̃",
        "OWN": "õʊ̃",
        "DX": "ɾ",
        "AYN": "ãɪ̃",
        "AAN": "ɑ̃",
        "UWN": "ũ",
        "NX": "ɾ̃",
        "AX": "ə",
        "EHN": "ɛ̃",
        "UHN": "ʊ̃",
        "AWN": "ãʊ̃",
        "AHN": "ʌ̃",
        "TQ": "ʔ",
        "IHN": "ɪ̃",
        "ERN": "ɹ̩̃",
        "OYN": "ɔ̃ɪ̃",
    }
)
