name: Lint with ruff

on:
  pull_request:
  push:
    branches: [ $default-branch ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: astral-sh/ruff-action@v3
        with:
          version: ">=0.14.1"
      - name: Lint with ruff
        run: |
          ruff check .